name: Cleanup PR

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on:
      group: default

    steps:
      - uses: SallaApp/.CI/worker-backend/cleanup@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cf_account_id: ${{ secrets.CF_ACCOUT_ID_SALLA_GROUP }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}
