name: Create Drafter
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create_draft:
    runs-on:
      group: default
    steps:
      - uses: SallaApp/.CI/create-draft@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          telegram_token: ${{ secrets.TELEGRAM_TOKEN_PRIVATE }}
          telegram_group: ${{ secrets.TELEGRAM_TO_PRIVATE }}
