name: "Lint PR"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  title:
    name: Validate PR title
    runs-on:
      group: default
    steps:
      - uses: SallaApp/.CI/lint-pr@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  branch:
    name: Validate branch name
    runs-on:
      group: default
    steps:
      - uses: SallaApp/.CI/lint-branch@master
